name: Build QMK firmware
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
# List of keymap json files to build
        keymap:
        - username.json
# End of json file list

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: stewartsoda/qmk_firmware
        ref: redragon_k715_pro_dev
        submodules: recursive

    # - name: Checkout userspace
    #   uses: actions/checkout@v3
    #   with:
    #     path: users/${{ github.actor }}

    - name: Build firmware
      run: qmk compile -kb redragon/k715_pro -km default

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: redragon_k715_pro_default
        path: |
          *.hex
          *.bin
          *.uf2