# This is a basic workflow that is manually triggered

name: Manual Build workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      repository:
        description: 'Which QMK repository you would like to build from'
        default: 'stewartsoda'
        type: choice
        options: [qmk, stewartsoda]
        required: true
      branch:
        description: 'The branch to build'
        required: true
        type: string
        default: 'redragon_k715_pro_dev'
      keyboard:
        description: 'The keyboard to build'
        default: 'redragon/k715_pro'
        type: string
        required: true
      keymap:
        description: 'The keymap to build'
        default: 'default'
        type: string
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  setup_env_and_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"

    - name: Install prerequisites
      run: |
        apt-get update
        apt-get install -y jq

    - name: Disable safe.directory check
      run: |
        git config --global --add safe.directory '*'

    - name: Checkout QMK Firmware
      uses: actions/checkout@v5
      with:
        repository: qmk/qmk_firmware
# Uncomment the following for develop branch
        ref: ${{ inputs.branch }}
        fetch-depth: 1
        persist-credentials: false
        submodules: recursive
    - name: Build firmware
      run: qmk compile -kb ${{ inputs.keyboard }} -km ${{ inputs.keymap }}

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: redragon_k715_pro_default
        if-no-files-found: ignore
        path: |
          *.bin
          *.hex
          *.uf2
